### ISSUE TITLE
Error when I press the cancel button and the popup gets stucked

### ISSUE THREAD

**Issue by ilianan** [tag1consulting/ckeditor_comment#5]
I tried to cancel the comment and gets stucked and repeat the words that I tried to comment.
And when I try to write on the popup it's gets stucked too and write very slow
I let a video that shows what is happening 
[nimbus-video.webm.zip](https://github.com/tag1consulting/ckeditor_comment/files/886836/nimbus-video.webm.zip)

**Comment by markcarver** [comment]
This project was never actually finished. See #6.
